R2000:
  transport: "tcp"
  scanner_ip: "192.168.0.9"
  # port: "3000" # optional
  device: "R2000"
  start_angle: -1800000
  max_num_points_scan: 0
  packet_type: "C"
  scan_topic: "/scan"
  frame_id: "scanner_link"
  watchdogtimeout: 60000
  watchdog: true
